### ISSUE TITLE
Translate custom messages misses multiline support

### ISSUE THREAD

**Issue by Pascal27** [nvuio/discord-translator#10]
The translate custom message feature doesn't support multiline messages. When making line breaks only the first line will be translated.

**Example:**
_Command:_ 
```
!t this to en: line 1
line 2
```
_Outcome:_ `line 1`
<img width="284" alt="bildschirmfoto 2018-03-03 um 23 11 54" src="https://user-images.githubusercontent.com/28492184/36939830-4e10b5dc-1f38-11e8-9c7f-e30923e1aedf.png">

**Comment by aziznatour** [comment]
Hello,

This has been fixed in v1.0 which will be released within 1-2 days.

<img src="http://puu.sh/zzWIG/2c273efe00.png">

Thanks for your feedback!
