### ISSUE TITLE
Multiple embeds are sometimes shown in the wrong order

### ISSUE THREAD

**Issue by Pascal27** [nvuio/discord-translator#11]
_Note: Not sure if that is an Discord issue or an issue with the bot, maybe there is a workaround for the problem._

When exceeding the char limit for one embed, the order gets sometimes messed up and seems to be random. So posting a message with 2000 characters for example and asking the bot to translate it, will show the message in 2 embeds and the order of the 2 embeds is not always correct.

**Comment by aziznatour** [comment]
Should not longer happen in v.1.0 after a system overhaul. Thanks for your report!
