### ISSUE TITLE
Add purge user command for auto translations origins/destinations

### ISSUE THREAD

**Issue by BrokeProtocol** [nvuio/discord-translator#8]
Let's say you have linked multiple channels together to automatically translate everything to each other.

>In #english —!translate channel to spanish from english for #spanish
>In #english — !translate channel to russian from english for #russian
>In #spanish — !translate channel to english from spanish for #english
>In #spanish — !translate channel to russian from spanish for #russian
>In #russian — !translate channel to english from russian for #english
>In #russian — !translate channel to spanish from russian for #spanish

If someone spams, posts inappropriate comments, or shares malware; you would have to delete every message manually including the bot translated messages.  The purge command will delete all users messages in all origin and destination channels, including all the messages the bot has translated. 

Command: 
!translate purge `<user> <number of messages>`
!translate purge @BP 50

i.e If you type the purge command in the #english channel it will check the origins and destinations of any active tasks, then the purge command will run on all channels if any are linked to #english channel.

**Comment by aziznatour** [comment]
Fixed in v.1.0
* Deletion of original message will delete all of its translations
* Bulk deletions supported as well
* Banning a member triggers deletions as well (if deletion option is set)
